#ifndef __DDR_CHUNKRESOURCE_UGLY2LOOKAT_SETUPEXE_H_INCLUDED__
#define __DDR_CHUNKRESOURCE_UGLY2LOOKAT_SETUPEXE_H_INCLUDED__

namespace DDRGadgets {

extern int gRES_SETUPEXE_len;
extern int gRES_SETUPEXE_ExtraLen;
extern char gRES_SETUPEXE_EData[];

}

#endif //__DDR_CHUNKRESOURCE_UGLY2LOOKAT_SETUPEXE_H_INCLUDED__

